export const DEFAULT_NULL = 'DEFAULT_NULL'
export const ON_SORT_CHEAP = 'ON_SORT_CHEAP'
export const ON_SORT_FAST = 'ON_SORT_FAST'
export const ON_SORT_OPTIMAL = 'ON_SORT_OPTIMAL'

export const TOGGLE_FILTER = 'TOGGLE_FILTER'

export const FETCH_TICKETS_REQUEST = 'FETCH_TICKETS_REQUEST'
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS'
export const FETCH_TICKETS_FAILURE = 'FETCH_TICKETS_FAILURE'

export const VIEW_MORE = 'VIEW_MORE'
